language: python
python:
  - "3.4"
before_install:
  - nvm install 7
  - node --version
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - pip install pep8
  - pip install coverage==4.3.4
  - pip install codeclimate-test-reporter
cache:
  directories:
  - $HOME/.yarn-cache
before_script:
  - yarn install
script:
  - yarn test
  - yarn compile
  - find ./tntfl -name \*.py -exec pep8 --ignore=E501 {} +
  - find . -name \*.cgi -exec pep8 --ignore=E501 {} +
  - python run_tests.py
  - coverage run --source=tntfl --omit=tntfl/test/* run_tests.py
  - codeclimate-test-reporter
