language: python
python:
  - "2.7"
before_install:
  - nvm install 7
  - node --version
  - pip install pep8
  - pip install coverage==4.3.4
  - pip install codeclimate-test-reporter
before_script:
  - npm install
script:
  - find . -name \*.py -exec pep8 --ignore=E501 {} +
  - npm test
  - npm run compile
  - python run_tests.py
  - coverage run --source=tntfl --omit=tntfl/test/* run_tests.py
  - codeclimate-test-reporter
